// Textos del carrito, checkout, pago con Payphone y consulta de pedidos.
export const cartCopy = {
  title: 'Tu carrito',
  close: 'Cerrar carrito',
  remove: 'Quitar',
  removeAria: (name: string) => `Quitar ${name} del carrito`,
  subtotal: 'Subtotal estimado',
  cardNote: 'Precio con tarjeta. El total final se calcula en el checkout.',
  viewCart: 'Ver carrito',
  checkout: 'Finalizar compra',
  continue: 'Seguir comprando',
  emptyTitle: 'Tu carrito está vacío',
  emptyText: 'Explora la tienda y agrega tus suplementos favoritos.',
  toShop: 'Ir a la tienda',
  freeShippingMissing: (amount: string) => `Te faltan ${amount} para el envío gratis`,
  freeShippingDone: 'Tu pedido tiene envío gratis',
  units: (n: number) => (n === 1 ? '1 producto' : `${n} productos`),
  pageEyebrow: 'Carrito',
}

export const checkoutCopy = {
  eyebrow: 'Finalizar compra',
  title: 'Tus datos y el pago',
  secure: 'Compra sin cuenta: solo necesitamos tus datos de envío.',
  steps: {
    contact: 'Datos de contacto',
    address: 'Dirección de envío',
    payment: 'Método de pago',
  },
  fields: {
    name: 'Nombre y apellido',
    email: 'Correo electrónico',
    phone: 'Teléfono celular',
    documentId: 'Cédula o RUC',
    province: 'Provincia',
    provincePlaceholder: 'Elige tu provincia',
    city: 'Ciudad',
    address: 'Dirección',
    addressPlaceholder: 'Calle principal, número y calle secundaria',
    reference: 'Referencia (opcional)',
    referencePlaceholder: 'Casa esquinera, portón negro…',
  },
  errors: {
    name: 'Escribe tu nombre completo',
    email: 'Escribe un correo válido',
    phone: 'Escribe un teléfono válido de 10 dígitos',
    documentId: 'Escribe una cédula (10 dígitos) o RUC (13 dígitos) válido',
    province: 'Elige tu provincia',
    city: 'Escribe tu ciudad',
    address: 'Escribe tu dirección de entrega',
    form: 'Revisa los datos marcados en rojo',
    cardUnavailable: 'Elige transferencia o pago contra entrega para completar tu pedido ahora.',
  },
  bestPrice: 'Mejor precio',
  saveVsCash: (amount: string) => `Ahorras ${amount} frente a pago contra entrega`,
  quoting: 'Calculando…',
  coupon: {
    toggle: '¿Tienes un cupón?',
    label: 'Código de cupón',
    placeholder: 'TEQUIEROVIDA20',
    apply: 'Aplicar',
    remove: 'Quitar cupón',
    applied: (code: string, percent: number) => `Cupón ${code} aplicado: ${percent}% de descuento`,
  },
  summary: {
    title: 'Resumen del pedido',
    subtotal: 'Subtotal',
    volume: 'Descuento por volumen',
    coupon: (code: string) => `Cupón ${code}`,
    shipping: 'Envío',
    free: 'Gratis',
    total: 'Total',
    qty: (n: number) => `Cantidad: ${n}`,
    volumeOff: (p: number) => `-${p}% por volumen`,
  },
  pay: (amount: string) => `Pagar ${amount}`,
  confirm: 'Confirmar pedido',
  processing: 'Procesando…',
  quoteError: 'No pudimos calcular el total. Revisa tu conexión e inténtalo otra vez.',
  retryQuote: 'Reintentar',
  cardSection: {
    eyebrow: 'Paga con tarjeta',
    title: (orderNumber: string) => `Pedido ${orderNumber}`,
    text: 'Ingresa los datos de tu tarjeta en el formulario seguro de Payphone.',
    expires: 'El formulario expira en 10 minutos. Si se vence, genera un nuevo intento.',
    newAttempt: 'Generar un nuevo intento',
    changeMethod: 'Prefiero otro método de pago',
    changeMethodWhatsapp: (orderNumber: string) =>
      `Hola Munavi, quiero pagar mi pedido ${orderNumber} con otro método de pago`,
  },
}

export const payphoneCopy = {
  loading: 'Cargando el formulario de pago seguro…',
  loadError: 'No pudimos cargar el formulario de pago. Revisa tu conexión y vuelve a intentarlo.',
  retry: 'Reintentar',
  secured: 'Pago procesado por Payphone. Munavi no guarda los datos de tu tarjeta.',
}

export const paymentResultCopy = {
  missingTitle: 'Faltan los datos del pago',
  missingText: 'Este enlace no trae la información de la transacción. Si ya pagaste, consulta tu pedido con tu número y correo.',
  lookup: 'Consultar mi pedido',
  confirmingTitle: 'Confirmando tu pago',
  confirmingText: 'No cierres esta página, tarda solo unos segundos.',
  approvedTitle: '¡Pago aprobado!',
  approvedText: 'Te enviamos un correo con el detalle de tu pedido.',
  orderNumber: 'Número de pedido',
  failedTitle: 'Tu pago no se completó',
  failedText: 'El pago fue rechazado o cancelado. No se hizo ningún cobro. Puedes intentarlo de nuevo.',
  retryPay: 'Reintentar el pago',
  whatsapp: 'Pagar con ayuda por WhatsApp',
  whatsappMessage: (orderNumber: string) => `Hola Munavi, mi pago del pedido ${orderNumber} no se completó. ¿Me ayudan?`,
  pendingTitle: 'Tu pago está en revisión',
  pendingText: 'Payphone todavía no confirma la transacción. Revisa el estado de tu pedido en unos minutos.',
  networkTitle: 'No pudimos confirmar tu pago',
  networkText: 'Hubo un problema de conexión. Tu pago no se pierde: vuelve a intentar la confirmación.',
  retryConfirm: 'Reintentar confirmación',
  viewOrder: 'Ver mi pedido',
  toShop: 'Seguir comprando',
  retryTitle: 'Reintentar el pago',
  retryMissing: 'Este enlace no trae el número de pedido o el correo.',
  retryLoading: 'Preparando un nuevo intento de pago…',
  retryErrorTitle: 'No se puede reintentar este pago',
}

export const orderCopy = {
  eyebrow: 'Tu pedido',
  title: (orderNumber: string) => `Pedido ${orderNumber}`,
  placed: (date: string) => `Realizado el ${date}`,
  loading: 'Buscando tu pedido…',
  notFoundTitle: 'No encontramos tu pedido',
  missingEmail: 'Para ver tu pedido necesitamos el correo con el que compraste.',
  lookup: 'Consultar con mi correo',
  retry: 'Reintentar',
  paymentMethod: 'Método de pago',
  shipTo: 'Envío a',
  contact: 'Contacto',
  track: 'Rastrear envío',
  timeline: ['Pedido recibido', 'Confirmado', 'Enviado', 'Entregado'],
  canceled: 'Este pedido fue cancelado. Si tienes dudas, escríbenos por WhatsApp.',
  failed: 'El pago con tarjeta no se completó.',
  retryPay: 'Reintentar el pago',
  instructions: {
    transfer: 'Transfiere el total a esta cuenta y envíanos el comprobante por WhatsApp. Despachamos cuando lo validamos.',
    cash_on_delivery: 'Pagas en efectivo al recibir tu pedido. Te contactaremos para coordinar la entrega.',
    card: 'Tu pago con tarjeta fue procesado por Payphone.',
    cardPending: 'Tu pago con tarjeta aún no se completa.',
  },
  bankTitle: 'Datos para la transferencia',
  bankMissing: 'Escríbenos por WhatsApp y te enviamos los datos de la cuenta.',
  copy: 'Copiar datos',
  copied: 'Datos copiados',
  clipboard: (info: string, amount: string, orderNumber: string) => `${info}\nMonto: ${amount}\nPedido: ${orderNumber}`,
  copyError: 'No se pudo copiar. Selecciona el texto y cópialo a mano.',
  sendProof: 'Enviar comprobante',
  proofMessage: (orderNumber: string) => `Hola Munavi, envío el comprobante de transferencia de mi pedido ${orderNumber}`,
  helpMessage: (orderNumber: string) => `Hola Munavi, tengo una consulta sobre mi pedido ${orderNumber}`,
  help: 'Ayuda con mi pedido',
  thanks: '¡Gracias por tu compra!',
  emailSent: 'Te enviamos un correo con el detalle.',
}

export const lookupCopy = {
  eyebrow: 'Mi pedido',
  title: 'Consulta tu pedido',
  text: 'Escribe el número de pedido que te llegó por correo y el correo con el que compraste.',
  orderNumber: 'Número de pedido',
  orderNumberPlaceholder: 'MUN-000123',
  email: 'Correo electrónico',
  submit: 'Ver mi pedido',
  required: 'Escribe tu número de pedido y tu correo',
  invalidEmail: 'Escribe un correo válido',
}
