// Textos de tarjetas, ficha de producto y tienda.
export const productCopy = {
  cardPrice: 'Precio con tarjeta',
  transfer: 'Transferencia',
  cashOnDelivery: 'Contra entrega',
  save: 'Ahorras',
  bestSeller: 'Más vendido',
  featured: 'Destacado',
  outOfStock: 'Agotado',
  flavors: (n: number) => (n === 1 ? '1 sabor' : `${n} sabores`),
  tier: (qty: number, percent: number) => `Lleva ${qty} y ahorra ${percent}%`,
  tiersTitle: 'Ahorra llevando más',
  tierActive: 'Aplicado',
  add: 'Agregar',
  chooseFlavor: 'Elegir sabor',
  added: 'Agregado al carrito',
  noImage: 'Imagen próximamente',
  noPrice: 'Precio por confirmar',
  noPriceHint: 'Escríbenos y te lo confirmamos',
  askPrice: 'Consultar por WhatsApp',
  askPriceShort: 'Consultar',
  askPriceMessage: (name: string, flavor?: string) =>
    `Hola Munavi, quiero información y precio de ${name}${flavor ? ` (${flavor})` : ''}`,
}

export const productDetailCopy = {
  back: 'Volver a la tienda',
  flavor: 'Sabor',
  quantity: 'Cantidad',
  decrease: 'Quitar uno',
  increase: 'Agregar uno',
  addToCart: 'Agregar al carrito',
  buyNow: 'Comprar ahora',
  unavailable: 'Sin stock en este sabor',
  gallery: 'Ver imagen',
  perks: [
    { icon: 'fa-solid fa-truck-fast', text: 'Envíos a todo Ecuador' },
    { icon: 'fa-solid fa-lock', text: 'Pago seguro con tarjeta, transferencia o contra entrega' },
    { icon: 'fa-solid fa-flask', text: 'Hecho en Ecuador con materia prima importada' },
  ],
  ask: '¿Tienes dudas? Pregúntanos por WhatsApp',
  askMessage: (name: string) => `Hola Munavi, tengo una duda sobre ${name}`,
  sections: {
    description: 'Descripción',
    benefits: 'Beneficios',
    presentation: 'Presentación',
    usage: 'Modo de uso',
    ingredients: 'Ingredientes',
    nutritionInfo: 'Información nutricional',
    warnings: 'Advertencias',
  },
  related: 'También te puede gustar',
  notFoundTitle: 'No encontramos este producto',
  notFoundText: 'Puede que ya no esté disponible o que el enlace haya cambiado.',
  errorTitle: 'No pudimos cargar el producto',
  retry: 'Reintentar',
  toShop: 'Ir a la tienda',
}

export const shopCopy = {
  eyebrow: 'Tienda',
  title: 'Todos los productos',
  text: 'Suplementos para ti y tu familia, hechos en Ecuador con materias primas importadas.',
  all: 'Todo',
  searchLabel: 'Buscar en la tienda',
  searchPlaceholder: 'Buscar por nombre o sabor',
  clearSearch: 'Limpiar búsqueda',
  results: (n: number) => (n === 1 ? '1 producto' : `${n} productos`),
  searchingFor: 'Resultados para',
  emptyTitle: 'No encontramos productos',
  emptyText: 'Prueba con otra búsqueda o explora todas las categorías.',
  emptyCategoryTitle: 'Esta categoría está por llenarse',
  emptyCategoryText: 'Muy pronto tendremos productos aquí. Mira el resto de la tienda mientras tanto.',
  seeAll: 'Ver todos los productos',
  errorTitle: 'No pudimos cargar la tienda',
  retry: 'Reintentar',
  prev: 'Anterior',
  next: 'Siguiente',
  page: (p: number, total: number) => `Página ${p} de ${total}`,
}
